apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: go-hpa
spec:
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 15
    scaleTargetRef:
        # apiVersion: app/v1
        apiVersion: extensions/v1
        kind: Deployment
        name: go-hpa